// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SewaRuangan.API.Data;

#nullable disable

namespace SewaRuangan.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SewaRuangan.API.Models.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_id");

                    b.Property<string>("CatatanAdmin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("catatan_admin");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DisetujuiPada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disetujui_pada");

                    b.Property<int>("JumlahPeserta")
                        .HasColumnType("integer")
                        .HasColumnName("jumlah_peserta");

                    b.Property<string>("Keperluan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("KodePeminjaman")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kode_peminjaman");

                    b.Property<int>("RuanganId")
                        .HasColumnType("integer")
                        .HasColumnName("ruangan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("menunggu")
                        .HasColumnName("status");

                    b.Property<DateTime>("TanggalPeminjaman")
                        .HasColumnType("date")
                        .HasColumnName("tanggal_peminjaman");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<TimeSpan>("WaktuMulai")
                        .HasColumnType("time")
                        .HasColumnName("waktu_mulai");

                    b.Property<TimeSpan>("WaktuSelesai")
                        .HasColumnType("time")
                        .HasColumnName("waktu_selesai");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("KodePeminjaman")
                        .IsUnique();

                    b.HasIndex("RuanganId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reservation_Time", "\"waktu_selesai\" > \"waktu_mulai\"");
                        });
                });

            modelBuilder.Entity("SewaRuangan.API.Models.Entities.Ruangan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Fasilitas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gedung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Kapasitas")
                        .HasColumnType("integer");

                    b.Property<string>("KodeRuangan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("kode_ruangan");

                    b.Property<int>("Lantai")
                        .HasColumnType("integer");

                    b.Property<string>("NamaRuangan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nama_ruangan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("tersedia");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("KodeRuangan")
                        .IsUnique();

                    b.ToTable("Ruangans", (string)null);
                });

            modelBuilder.Entity("SewaRuangan.API.Models.Entities.StatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Catatan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("catatan");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("reservation_id");

                    b.Property<string>("StatusSebelum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_sebelum");

                    b.Property<string>("StatusSesudah")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_sesudah");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("ReservationId");

                    b.ToTable("StatusHistories", (string)null);
                });

            modelBuilder.Entity("SewaRuangan.API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SewaRuangan.API.Models.Entities.Reservation", b =>
                {
                    b.HasOne("SewaRuangan.API.Models.Entities.User", "Admin")
                        .WithMany("ApprovedReservations")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SewaRuangan.API.Models.Entities.Ruangan", "Ruangan")
                        .WithMany("Reservations")
                        .HasForeignKey("RuanganId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SewaRuangan.API.Models.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Ruangan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SewaRuangan.API.Models.Entities.StatusHistory", b =>
                {
                    b.HasOne("SewaRuangan.API.Models.Entities.User", "User")
                        .WithMany("StatusHistories")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SewaRuangan.API.Models.Entities.Reservation", "Reservation")
                        .WithMany("StatusHistories")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SewaRuangan.API.Models.Entities.Reservation", b =>
                {
                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("SewaRuangan.API.Models.Entities.Ruangan", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SewaRuangan.API.Models.Entities.User", b =>
                {
                    b.Navigation("ApprovedReservations");

                    b.Navigation("Reservations");

                    b.Navigation("StatusHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
